export USERNAME='exampleuser'
export URL='vpn.example.com'
export HOMEPAGE='example.com'
export PIN='000000'
export PASSWORD='password'
export RSATOKEN=''
export COMPOSEOPTS='--abort-on-container-exit'
