---
version: '3'
services:
  openconnect:
    image: mefdock/docker-arch-openconnect
    # Override the entrypoint to allow us to provide the password / RSA on
    # stdin
    environment:
      - USERNAME=$USERNAME
      - URL=$URL
      - HOMEPAGE=$HOMEPAGE
      - PIN=$PIN
      - PASSWORD=$PASSWORD
      - RSA=$RSA
    volumes:
      - ./entrypoint.sh:/entrypoint.sh
    entrypoint: /entrypoint.sh
    cap_add:
      - NET_ADMIN

  firefox:
    image: mefdock/docker-arch-firefox
    environment:
      - DISPLAY=$DISPLAY
    command: $HOMEPAGE
    shm_size: 2g
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ${HOME}:${HOME}:ro
      - ${DOWNLOADS}:/downloads
    network_mode: service:openconnect
    depends_on:
      - openconnect
