#!/bin/bash

# Ensure latest containers are pulled
# Ignore 'variable is not set' errors
docker-compose pull 2>/dev/null

# Load config settings
source ./config.sh

# Get the VPN URL from the user if we haven't got one.
if [ "${URL}" = "" ]; then
	read -p 'Enter VPN URL: ' -r URL
	export URL
fi;

# Default Homepage if not specified
if [ "${HOMEPAGE}" = "" ]; then
	HOMEPAGE='google.com'
	export HOMEPAGE
fi;

# Get the Username from the user if we haven't got one.
if [ "${USERNAME}" = "" ]; then
	read -p 'Enter Username: ' -r USERNAME
	export USERNAME
fi;

# Get the password from the user if we haven't got one.
if [ "${PASSWORD}" = "" ]; then
	read -p 'Enter Password: ' -rs PASSWORD
	echo ""
	export PASSWORD
fi;

# Get the password from the user if we haven't got one.
if [ "${PIN}" = "" ]; then
	read -p 'Enter RSA Token Pin: ' -rs PIN
	echo ""
	export PIN
fi;

# Get RSA token if we have been provided a seed
STOKEN=`which stoken`
if [ "${STOKEN}" != "" -a "${RSATOKEN}" != "" ]; then
	export RSA=`${STOKEN} --token "${RSATOKEN}" 2>&1`
fi;
# Get the RSA token from the user if we haven't got one.
if [ "${RSA}" = "" ]; then
	read -p 'Enter RSA Token: ' -rs RSA
	export RSA
fi;

# Allow access to xserver from docker
xhost "+local:"

# Startup
docker-compose up ${COMPOSEOPTS}

# Cleanup
docker-compose down
xhost "-local:"
