#!/bin/bash

# Ensure latest containers are pulled
# Ignore 'variable is not set' errors
docker-compose pull 2>/dev/null

# Load config settings
source ./config.sh

# Allow access to xserver from docker
xhost "+local:"

# Startup
docker-compose up

# Cleanup
docker-compose down
xhost "-local:"
